### ISSUE TITLE
DLL inject

### ISSUE THREAD

**Issue by 123biglikeatree** [15H15M/Dota-2-tool-for-badass-boiz#3]
Hi, when i inject the dll into the game, nothing happens. Are there any specific methods how to use? Thanks.

**Comment by 15H15M** [comment]
Kycb!
Dota 2 has no more DirectX 9 render, that menu is based on. 
I already done with add d11 hook, but i need update all functions and logic.
One unreleased update that i coded in a hours before valve cutted out d3d9 is also need render update.

Working on. Dont miss me 👀

**Comment by 123biglikeatree** [comment]
Thanks for the reply brother. I'm watching your update, take your time bro. Love you!

**Comment by 123biglikeatree** [comment]
Hi, when i inject the latest dll nothing happens again. Tried compiling it myself, and when i inject my dll it crashes the game. Any tips? Thanks!

**Comment by 123biglikeatree** [comment]
Hi, latest dll when injected crashes even when connected to a game. Any tips? Thanks.
